name: "tool-reasoning"
tool_command: "python"
args:
  - "-m"
  - "src.tool.mcp_servers.reasoning_mcp_server"
env:
# If OpenAI API key and Anthropic API key are both provided, OpenAI will be used.
# These values will be loaded from the .env file at runtime
  OPENAI_API_KEY: "${oc.env:OPENAI_API_KEY}"
  OPENAI_BASE_URL: "${oc.env:OPENAI_BASE_URL,https://openrouter.ai/api/v1}"
  OPENAI_MODEL_NAME: "${oc.env:OPENAI_MODEL_NAME,anthropic/claude-3-7-sonnet:thinking}"
  ANTHROPIC_API_KEY: "${oc.env:ANTHROPIC_API_KEY, null}"
  ANTHROPIC_BASE_URL: "${oc.env:ANTHROPIC_BASE_URL,https://api.anthropic.com}"
  ANTHROPIC_MODEL_NAME: "${oc.env:ANTHROPIC_MODEL_NAME,claude-3-7-sonnet-20250219}"
  